import { OpenAI } from 'openai';

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export type VoiceIntent = 
  | 'UPLOAD_PRESCRIPTION' 
  | 'ADD_MEDICINE' 
  | 'SHOW_MEDICINES' 
  | 'CHECK_INTERACTION' 
  | 'GET_REMINDER'
  | 'UNKNOWN';

export interface ParsedIntent {
  intent: VoiceIntent;
  confidence: number;
  extractedEntities?: Record<string, string>;
  message?: string;
}

/**
 * Transforms unstructured dictated queries into strict actionable NoSQL Intents.
 * 
 * @param transcribedText - The raw STT string generated by Sarvam.
 * @returns {Promise<ParsedIntent>} Formatted command explicitly mapped to internal features.
 */
export async function parseVoiceIntent(transcribedText: string): Promise<ParsedIntent> {
  if (!transcribedText.trim()) {
    return { intent: 'UNKNOWN', confidence: 0 };
  }

  console.log(`[Intent Parser] Analyzing command semantics: "${transcribedText}"`);

  const systemPrompt = `
You are the linguistic routing engine for NeuraMed, an AI-powered medical application.
Your goal is to parse user voice commands into exact system intents.

AVAILABLE INTENTS:
1. UPLOAD_PRESCRIPTION: The user wants to scan, read, or upload a medical prescription.
2. ADD_MEDICINE: The user is explicitly stating they want to add a new drug to their active inventory. Extract the drug name if possible.
3. SHOW_MEDICINES: The user wants to view their current medications or inventory.
4. CHECK_INTERACTION: The user is asking if two or more drugs are safe to take together. Extract the drug names.
5. GET_REMINDER: The user wants to know when their next medicine is due, or their schedule.
6. UNKNOWN: The request is conversational, unclear, or doesn't map to the standard NeuraMed features.

RETURN STRICT JSON matching this schema:
{
  "intent": "<ONE OF THE ENUMS ABOVE>",
  "confidence": <0.0 to 1.0>,
  "extractedEntities": {
    // any named entities like "drug1": "Aspirin", "drug2": "Warfarin" etc.
  },
  "message": "<Any conversational acknowledgment>"
}
`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Voice Query:\n"${transcribedText}"` }
      ],
      response_format: { type: "json_object" },
      temperature: 0.1, // Strict logical routing 
      max_tokens: 500
    });

    const content = response.choices[0].message.content;
    if (!content) throw new Error("OpenAI router returned an empty block.");

    const parsedJson = JSON.parse(content) as ParsedIntent;
    
    // Safety check forcing unknown if the LLM hallucinates an enum
    const validIntents: VoiceIntent[] = ['UPLOAD_PRESCRIPTION', 'ADD_MEDICINE', 'SHOW_MEDICINES', 'CHECK_INTERACTION', 'GET_REMINDER', 'UNKNOWN'];
    if (!validIntents.includes(parsedJson.intent)) {
      parsedJson.intent = 'UNKNOWN';
    }

    console.log(`[Intent Parser] Semantics strictly mapped to -> [${parsedJson.intent}]`);
    return parsedJson;

  } catch (error: any) {
    console.error("[Intent Parser] Semantic Mapping Failure:", error.message);
    throw new Error(`Intent parsing failed: ${error.message}`);
  }
}
